### ISSUE TITLE
Simple question about "Speedy-Rendering"

### ISSUE THREAD

**Issue by EstherMoellman** [eladkarako/chrome_extensions#1]
Hi Elad! 

First of all, thank you for all your add-ons/extensions. Amazing work!

Second, it is very sad to know that you have had tons of difficulties trying to share your work at Firefox/Chrome. I couldn't believe all your huge work at Mozilla AMO disappeared... for the second time! What a disappointment/frustration! Luck for me, all your stuff is here! :)

Third, simple question: I am interested on "Speedy-Rendering". I extracted your CSS' script, and inserted it into Stylus (add-on). However, I did several tests, measured with several tools, and haven't seen browser performance increments/differences. So, I wonder if am I doing something wrong? Perhaps your CSS' script is not meant to work at Stylus? Does it need to work at userChrome? Or userContent?

Perhaps did I make some mistake with your code? Here is what I extracted: https://pastebin.com/JE7ap4SM

I already know that most of your add-ons/extensions are scripts you used for years. So based on your great experience, do you have for me any other CSS' recommendations I can add to your CSS' "Speedy-Rendering" script?

Thanks in advance!

PS: I have always the latest Firefox Nightly + WebRender.

**Comment by eladkarako** [comment]
Hi, 
No. CSS is CSS. 

perhaps the Speedy-Rendering web-extension does so little benefit because the content you are trying to view is not too demanding or already quite well optimized.

The Speedy-Rendering web-extension improve scrolling speed by correcting the "leakage of content" on the the root from body, disables advanced text-features embedded in the font you use, removes the 300ms click-delay (for mobile devices where zoom-gesture by click is possible), it also allows page rendering before the page-embedded font downloads so the page is shown faster. shorten transition animation time to zero so you'll have no delay (but less pretty animation) and normalize the page layout.
You can also try an additional smoothing rendering by favoring a GPU-assisted rendering when possible with this at the bottom of the rules:
```css
/*░░░░░░░░░░░░░░░░░░░░░░░░
  ░ enable GPU-rendering.░
  ░░░░░░░░░░░░░░░░░░░░░░░░*/
/*-------------------------------------------------------------------enable a GPU-assisted rendering.*/
             -webkit-transform: translateZ(0);
                -moz-transform: translateZ(0);
                 -ms-transform: translateZ(0);
                  -o-transform: translateZ(0);
                     transform: translateZ(0);
             -webkit-transform: translate3d(0,0,0);
                -moz-transform: translate3d(0,0,0);
                 -ms-transform: translate3d(0,0,0);
                  -o-transform: translate3d(0,0,0);
                     transform: translate3d(0,0,0);
/*-------------------------------------------------------------------fix flickering.*/
   -webkit-backface-visibility: hidden;
      -moz-backface-visibility: hidden;
       -ms-backface-visibility: hidden;
        -o-backface-visibility: hidden;
           backface-visibility: hidden;
           -webkit-perspective: 1000;
              -moz-perspective: 1000;
               -ms-perspective: 1000;
                -o-perspective: 1000;
                   perspective: 1000;
```

**Comment by EstherMoellman** [comment]
Hi @eladkarako ! Many thanks for your answer.

Loved your GPU-webrender script. I'll test today!
I am interested in all your CSS' codes focused in browser performance improvements (CPU, RAM, speed etc). So please, always feel free to share with me your scripts, suggestions, experiments etc. Any recommendation you have about improving Firefox Nightly performance... it will be more than welcome.

I just will need to apologize because is not clear to me if your "no" applies to Stylus, userChrome, userContent etc. I am not an expert Elad, and in order to avoid mistakes, I prefer to ask you again: May I use your CSS' script at Stylus? userChrome? userContent?

Thank you once again!

**Comment by eladkarako** [comment]
I've edited my answer above...

note that GPU-assist is a bit risky since some websites does use transform for placing items in the x-y-z axis on the page (Google search page for example, it disabled the search query textbox at the top of the page) but as long you're not having issues with it on your website it should work fine for you.
since those rules are pure CSS you can either append them to the generated 'Stylus' output or make sure they do not break afterwards.

**Comment by EstherMoellman** [comment]
@eladkarako , my question was related just to Firefox (not other product). At Firefox is possible to use CSS basically in 3 different ways:
a) Add-ons like Stylus, where the CSS' code is inserted.
b) "userChrome" folder (at "chrome" folder in "profile" folder).
c) "userContent" folder (at "chrome" folder in "profile" folder).

The option "a)" is limited by AMO' rules, so CSS' scripts are also going to be limited by AMO' rules.
Option "b)" applies to CSS (unrestrictedly) affecting Firefox' UI (independently of AMO).
Option "c" applies to CSS (unrestrictedly) affecting webpages (independently of AMO).

And my question to you was "where to apply your CSS' code".
But don't worry, right now I am starting to test everything, and I will find out which one (of the 3) is the best place for your CSS' script.

Thanks a lot again, and have a nice weekend!

**Comment by eladkarako** [comment]
it's best not to think about it too much (I've used to when I've wrote userscripts),
this is done by the web-extension itself, in several stages of the life-cycle of the page, to every iframe in it (that's why injecting CSS with a web-extension is so darn useful) in that part:

```json
, "content_scripts"         : [ {"css": [ "resources/at_document_start.css" ], "all_frames": true, "match_about_blank": true, "matches": [ "*://*/*" ], "run_at": "document_start" }
                              , {"css": [ "resources/at_document_end.css"   ], "all_frames": true, "match_about_blank": true, "matches": [ "*://*/*" ], "run_at": "document_end"   }
                              , {"css": [ "resources/at_document_idle.css"  ], "all_frames": true, "match_about_blank": true, "matches": [ "*://*/*" ], "run_at": "document_idle"  }
                              ]
```

If you're writing a different mechanism the rule-of-thumb is that the CSS rules are to be injected as near as possible to the 'client-side'.

**Comment by EstherMoellman** [comment]
Yeah, but trying to gain performance, I avoided to install your Speedy-Rendering add-on (avoiding the JS page injection). So I extracted your CSS' script (in order to use directly at Stylus, or userChrome/userContent folders). That's the reason I mentioned you that my interest are "your CSS' scripts" (not add-ons). Absolutely nothing against your add-ons! It is just that if I use your CSS' scripts directly at userChrome/userContent folder, I gain a bit more browser performance. Add-ons (even the lightweights) always are heavier than CSS applied directly at userChrome, userContent. Of course, one add-on never will make any browser performance difference. But after accumulating a bunch of add-ons, Firefox becomes a heavy elephant. So, if I can and when I can, I always avoid add-ons, always preferring to use directly CSS.

**Comment by eladkarako** [comment]
>I always avoid add-ons, always preferring to use directly CSS.

understandable.

btw
>avoiding the JS page injection

there are no JS page injections.
the CSS injections are managed by the browser itself, in a very efficient manner.

**Comment by EstherMoellman** [comment]
@eladkarako  , thanks for your comments. Please, let me change subject:

My name is Karen, I am a student (Physics), and one of my hobbies is to customize Firefox (Nightly), sharing my experiences with a small club (200 users in 8 different countries). However, I am not an expert, never took a CSS' lesson (shame on me), but I like to make tests, just for the fun... is just a hobble.

I am telling you all this, because you may have interest in my latest experiment: A webpage-global-dark-theme (specially) focused on browser performance. At the bottom of this message I'm attaching you my CSS' script, including the basic details, explanations and instructions. It is a small script (compared to other similar scripts). But yeah, it is far away of being perfect, it is a work in progress (embryonic state), and it reflects my low CSS' know-how level.

Basically two things are needed:
a) My CSS' script needs to be improved.
b) A whitelist needs to be created for this add-on:  https://addons.mozilla.org/en-US/firefox/addon/toggle-darkmode (I'm in contact with the Dev, he is a great guy, but at first sight he doesn't know how to make a whitelist to his add-on).

At Firefox' AMO, webpage-darker-add-ons have around 150.000 users. An there are more than 50.000 users at userstyles.org messing up with Global Dark Themes. These are official numbers, but unofficially, I am sure that thousands of users are using some kind of webpage-darkening alternative. So, who knows?, you may be interested... I hope so!... it might be great because you have a huge knowledge at JS, CSS etc. But if you are not interested, is OK, no problem! Please, feel free to do what you want to do, what you can do, and when you want/can do. It is just for the fun! 

I guess you are Sabra and speak Hebrew. For a summer-period I took some courses at the Hebrew University, so I should understand a word or two of your Hebrew (LOL). 

Thanks in advance,

My CSS' script: https://pastebin.com/CUUYy84t

**Comment by eladkarako** [comment]
@EstherMoellman It is lovely to know you Karen.
