### ISSUE TITLE
[Feature Request] Complete API blocker with @eladkarako' firewall blocking method

### ISSUE THREAD

**Issue by Decopi** [eladkarako/chrome_extensions#12]
Thank you @eladkarako  for answering my previous question. Very nice and complete explanation from your side.
Please, sorry for opening a new issue, you closed my previous issue, but you also blocked there further comments.
So based on you answer, I'm opening a new request to you:

If I well understood you, the hard work already was done at [WebAPIBlocker](https://addons.mozilla.org/en-US/firefox/addon/webapi-blocker/) by listing most of the APIs. Just the blocking method needs to be improved. So, any chance that you may be interested in this challenge? WebAPIBlocker is an open source (License Mozilla Public License, version 2.0), so please, can you take advantage of this add-on, and improve it with your firewall blocking method?

An API blocker existed 2 years ago ([WeAPIManager](https://addons.mozilla.org/en-US/firefox/addon/webapi-manager/)), but the add-on is abandoned.
So, nowadays for blocking APIs, only WebAPIBlocker and your add-ons exists.
IMO, WebAPIBlocker is unusable as it is now, not just because the blocking method you described, but because it is unfriendly. Most of the users can't block APIs just from a raw long list of API' names.
In the other hand, you have few API blockers, with great blocking method.
In brief, one add-on has lots of APIs but with weak blocking method, and your add-ons have few APIs with strong blocking method.
So, the question to you is if you may be interested on building something like the abandoned WebAPIManager? Something that will merge the best: Lot of APIs, and Strong blocking method. An add-on that will include the most important APIs, with your strong firewall blocking method, and with 3 blocking modes (Light, Conservative, Aggressive) helping users to deal friendly with the blocking functions.

What do you say?
Interested?

If you accept, I will be happy to help you testing your prototypes.

Once again, thank you in advance!

**Comment by eladkarako** [comment]
I don't know about "hard work"
you can just run this from the console to get a list of all the functions under window:
```javascript
for(a in window) if("function" === typeof window[a]) console.log(a)
```

**Comment by eladkarako** [comment]
@Decopi 
BTW. you're GitHub account looks empty, did you've just created it?
