### ISSUE TITLE
UserAgent

### ISSUE THREAD

**Issue by jorg35** [eladkarako/chrome_extensions#14]
Where is UserAgent for Firefox ?

**Comment by eladkarako** [comment]
@jorg35 
mmmm... let me check...

**Comment by eladkarako** [comment]
Ahaa, it was really lame ("basic"), used a hard-coded useragent 
(although mocked both JavaScript and pre-requested connections) 
so I didn't bother generating a signed XPI from the Firefox store (generating a web-extension page is a huge waste of time, and it takes couple of days for the web-extension to be approved.. :|)

you can get <a href="https://github.com/eladkarako/chrome_extensions/releases/download/LatestChrome/UserAgent_1.0.0.5.zip">https://github.com/eladkarako/chrome_extensions/releases/download/LatestChrome/UserAgent_1.0.0.5.zip</a>, extract it, and load it with Firefox (same code) with
Tools - Add-ons - (on the 'gear' button to the right) click 'Debug Add-ons'
(or open <code>about:debugging#/runtime/this-firefox</code>)
then click the button saying 'Load Temporary Add-on...', browse the folder you've extracted from the zip above, and double click the manifest file, 
you can have a try out until you close down your Firefox (or unload the web-extension) to see how lame it is...

If you'll find it useful afterwards, I'll go ahead and generate an XPI for you. :|

**Comment by eladkarako** [comment]
@jorg35 nevermind, 
here it is:
https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/useragent-1.0.0.5-an+fx.xpi
