### ISSUE TITLE
Suddenly I am having a problem.

### ISSUE THREAD

**Issue by divinenews** [eladkarako/chrome_extensions#16]
UPDATE: Disregard my problem with the extension.  My problem is with something else. Even when I turn off the extension in Chrome, I still am having problems.
Thank you for all you do and keep up the good work.

**Comment by eladkarako** [comment]
I assume you were talking about <a href="https://github.com/eladkarako/chrome_extensions/tree/store/Boostaler">Boostaler</a>, 
which speeds up some of the network-responds and utilize a new feature by the browser which is a background resource-downloading, when switching ON/OFF the web-extension you might 'hit' a case where the browser does not fully load the resources as well as it should, 
in most of the cases you can reload the page and resources by pressing <kbd>SHIFT</kbd>+<kbd>F5</kbd>, or globally clear all of the browser cache using <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>DEL</kbd> (be careful not to remove anything you wish to keep such as cookies). 
Feel free to re-open/comment if you'll ever need an assistance or clarification, 
if you wish to walk through the source-code, you can download any XPI-file (a Firefox addon) from the release section and unzip it, the fully readable, non-minified source can help you understand how each web-extension works.
