### ISSUE TITLE
Ellipsis-fix where to download?

### ISSUE THREAD

**Issue by OmTatSat** [eladkarako/chrome_extensions#17]
Hello, where i can download Ellipsis-fix addon?

**Comment by eladkarako** [comment]
release section. 
there are two, Firefox (click, "allow", install) and Chrome (download zip, unzip somewhere, chrome extensions tab - 1. activate developer-mode, 2. load unpacked extension).

![2020-03-23_162949](https://user-images.githubusercontent.com/415238/77327457-f2063f00-6d23-11ea-9170-9cd02ef87ddf.jpg)

![2020-03-23_163148](https://user-images.githubusercontent.com/415238/77327487-fa5e7a00-6d23-11ea-8339-4b0a66e632bf.jpg)

![2020-03-23_163637](https://user-images.githubusercontent.com/415238/77327692-427d9c80-6d24-11ea-8ea3-f3b557a6ec65.jpg)
