### ISSUE TITLE
UnLazy not working on imdb

### ISSUE THREAD

**Issue by nijazm** [eladkarako/chrome_extensions#18]
Please add support for that website, I noticed that it does not work on any movie or list page, and does not detect anything (no numbers on icon in firefox). Your extension works perfect with wikihow tough and it really speeds up loading too, not just sparing my hands from scrolling!

**Comment by eladkarako** [comment]
oh thanks for notifying me, 
I'll check right away.

**Comment by eladkarako** [comment]
nice discovery! 

imdb puts the real SRC inside an attribute named <code>loadlate</code>.
also, if the page disables JavaScript, it tries to use the built-in lazyloading of the browser (new browsers have it) by placing <code>loading="lazy"</code> attribute on-to the IMG-element.

![2020-03-23_164938](https://user-images.githubusercontent.com/415238/77331685-bf5f4500-6d29-11ea-8fd2-afcf993f67df.jpg)

(really just note to myself..)

**Comment by eladkarako** [comment]
Right, I've updated the Chrome web-extension, 
which you can find in https://github.com/eladkarako/chrome_extensions/releases/tag/LatestChrome 
sadly Mozilla takes forever to sign web-extensions, so I'll just update it later (might took up to several days! _I know right!?!?_).

**Comment by eladkarako** [comment]
<blockquote><del>sadly Mozilla takes forever to sign web-extensions, so I'll just update it later (might took up to several days! I know right!?!?).</del></blockquote>

Hmmm... nevermind, it got approved right away for some reason. 
get the latest XPI from here: https://github.com/eladkarako/chrome_extensions/releases/tag/LatestFirefox
