### ISSUE TITLE
Aliexpress and ellipsis_fix-1.0.1.14-an+fx.xpi

### ISSUE THREAD

**Issue by OmTatSat** [eladkarako/chrome_extensions#19]
Hello I have a bug at https://aliexpress.ru/af/trimmer.html?d=y&origin=n&SearchText=trimmer&catId=0&initiative_id=SB_20200323075838
Are this can be fixed?

**Comment by eladkarako** [comment]
what is the nature of the bug?

**Comment by OmTatSat** [comment]
I see with addon //aliexpress.ru/item/400077... instead Машинка машинки для стри... without addon. But ellipsis is there with or without addon.
I can give you a screenshot if it needed.

**Comment by eladkarako** [comment]
I have an issue opening aliexpress links on my machine (I've blocked the domains long ago on my entire network due to the website being hacked several times and the user's details being leaked), 
so I can not test it right now, 

the web-extension replaces the Unicode character <code>…</code> and the string sequences <code>...</code> and <code>..&gt;</code> with the HREF-attribute, 
<strong>but</strong> it is also VERY specific in fixing <code>A</code>-elements, 
I assume there is something in the links that prevents the fix. 

If you can right-click the link and choose "inspect element", 
and paste it in here I can try to find out if I can fix it without testing it, 
since I rather keep blocking the aliexpress domains in my network. Sorry..

In the meantime I'm tagging this bug as 'won't fix'.

**Comment by OmTatSat** [comment]
I see. 
I can provide any info is needed to fix bug.
So in "inspect element" i have:

internal html
`SOOCAS N1 нос Xiaomi Mijia триммер для волос Электрический с крышкой ухо Бритва для волос Xiaomi Бритва для мужчин портативный клипер удаление Безопасны...`

external html
`<a data-p4p="true" class="item-title affiliate-attached" href="//aliexpress.ru/item/32962712896.html?spm=a2g0o.productlist.0.0.13b72f55CvRjnr&amp;s=p&amp;ad_pvid=20200329020440839243866127660005222529_1&amp;algo_pvid=a48d2576-faa5-4099-a548-81c4e0bedac1&amp;algo_expid=a48d2576-faa5-4099-a548-81c4e0bedac1-0&amp;btsid=0b8b034115854726796315030e857e&amp;ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_" title="SOOCAS N1 нос Xiaomi Mijia триммер для волос Электрический с крышкой ухо Бритва для волос Xiaomi Бритва для мужчин портативный клипер удаление Безопасны..." target="_blank" data-spm-anchor-id="a2g0o.productlist.0.0">SOOCAS N1 нос Xiaomi Mijia триммер для волос Электрический с крышкой ухо Бритва для волос Xiaomi Бритва для мужчин портативный клипер удаление Безопасны...</a>`

css-selector
`.list-items > div:nth-child(1) > li:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2)`

css path
`html.gr__aliexpress_ru body.aliexpress_superstar_plugin_present.alisuperstar-website-aliexpress div#root div.glosearch-wrap div.page-content div.main-content div.right-menu div.product-container div.gallery-wrap.product-list ul.list-items div li.list-item div.gallery.product-card.middle-place div.product-info div.hover-help div.item-title-wrap a.item-title.affiliate-attached
`
xpath
`/html/body/div[3]/div/div/div[2]/div[2]/div/div[2]/ul/div[1]/li[1]/div/div[2]/div/div[1]/a`

**Comment by eladkarako** [comment]
thanks!


the web-extebstion works as it should, 
there is no full description available, the '...' are a part of the internal text of the 'A' element and the title too.

If you'll save the page as HTML and upload it in here (make sure you log off your account first), I would check if a full description is available somewhere near the link (sometimes there is a DIV container with additional information).

**Comment by OmTatSat** [comment]
Here it is saved page
[trimmer с бесплатной доставкой на AliExpress.zip](https://github.com/eladkarako/chrome_extensions/files/4399301/trimmer.AliExpress.zip)

**Comment by eladkarako** [comment]
Appreciated, will debug it soon along with the new (much faster) version of UnLazy I will release. (no ETA just yet...)

**Comment by OmTatSat** [comment]
Thank you, I look forward to
