### ISSUE TITLE
UnLazy: Image broken on kotaku.com

### ISSUE THREAD

**Issue by Peuj** [eladkarako/chrome_extensions#2]
**Describe the bug**
I cannot see the image, the image links seem broken.

**To Reproduce**
Go to https://kotaku.com/blizzard-responds-to-accusations-of-censorship-in-heart-1836058159
I cannot see the image, the image links seem broken.
If I disable UnLazy and reload the page the images are visible.

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/6862131/60656178-4e9c9380-9e4f-11e9-97f0-1328649770e8.png)

Broken:
![image](https://user-images.githubusercontent.com/6862131/60656263-712eac80-9e4f-11e9-9f24-eddc9bc13152.png)

**Desktop (please complete the following information):**
 Windows 10 and Firefox 67.0.4

**Comment by eladkarako** [comment]
Thanks, for helping me fix a little bug, 
the web-extension does a better job parsing cases where there is a 'picture->src/src/src...' chain, 
where the last one has an image fallback with <code>data-srcset</code> that includes more than one URL.

I've just fixed and and uploaded the fixed version (<code>8.0.2.22</code>),
it might be a while until Mozilla and Chrome will actually review and publish the web-extension :|
but you can get it for Chrome (as a zip to load in 'developer mode') in a few moments...

reference:
https://github.com/eladkarako/chrome_extensions/commit/4a320859eedb08f54ba2a6dba7cc2a9a0bf5aa5a
