### ISSUE TITLE
wikihow displays waiting animation on images and images being larger size

### ISSUE THREAD

**Issue by nijazm** [eladkarako/chrome_extensions#20]
When I go to some wikihow category or article, like this:
https://www.wikihow.com/Category:Cars-%26-Other-Vehicles
while unlazy is enabled in chrome last version (80)
any image which i did not manually see (lazy load) during page loading are later stuck with waiting animation of 3 circles after page loads, although images are loaded, they're behind such animations
meaning if i did not lazy load it by manually scroller over it visible screen, just like before installing unlazy
When I disable unlazy then although I have to lazy load images by scrolling, they do not keep circles animation after they get loaded

Also I think jpg and other images are loaded in place where webp should be, and i think webp would be better because of smaller size, and get stored in cache during first loading, while your extension download some different images not stored in cache during initial load of page

one image element while using unlazy:

`<img id="5e7b0f04a7820" alt="" class="" loading="lazy" unlazy="" src="https://www.wikihow.com/images/thumb/7/76/Drive-at-Night-Step-17-Version-2.jpg/-crop-375-321-375px-nowatermark-Drive-at-Night-Step-17-Version-2.jpg" style="">`

one image element when not using unlazy:

`<img data-src="https://www.wikihow.com/images/thumb/7/76/Drive-at-Night-Step-17-Version-2.jpg/-crop-375-321-375px-nowatermark-Drive-at-Night-Step-17-Version-2.jpg" id="5e7b0f04a7820" alt="" class="" loading="lazy" src="https://www.wikihow.com/images/thumb/7/76/Drive-at-Night-Step-17-Version-2.jpg/-crop-375-321-375px-nowatermark-Drive-at-Night-Step-17-Version-2.jpg.webp">`

Yes, now I verified via network monitor in chrome that when your extension is not installed then webp images are loaded, and in this case size of image is 5174 bytes, while when your extension is loaded then jpg image is loaded with size 11186 bytes

Looks like there is no circles animation bug in firefox, but maybe webp problem is.

**Comment by eladkarako** [comment]
This is a known issue, 
I had to favor <code>data-src</code> and any lazyloading related attributes and the original <code>SRC</code> in-order to make the web-extension "non-website specific".
