### ISSUE TITLE
API-Killer-WebSockets is injecting strings in some text forms

### ISSUE THREAD

**Issue by SebastianTrautwein** [eladkarako/chrome_extensions#5]
**Describe the bug**
When using API-Killer-WebSockets in conjunction with TinyMCE HTML Editor the addon inserts a lot of unwanted strings into the editors text field. The injected text varies with every refresh of the text field. (My explanation is easier to understand if you look at the screenshots below.)

This issue happens also with:
- API-Killer-Beacon
- API-Killer-GeoLocation
- API-Killer-WebAssembly

**To Reproduce**
It's hard to reproduce for you since there is no free version of TinyMCE. I might be able to work something out for you but I hope you can see what the issue is based on my information without actually reproducing it.

Basically I use the TinyMCE editor, click on preview and then API-Killer-WebSockets writes a lot of text into the text field. (See screenshot and gist.)

**Expected behavior**
API-Killer-WebSockets only blocks websockets and does not modify anything else.

**Screenshots**
![Text Injection in preview mode](https://user-images.githubusercontent.com/46688299/61578600-ebbb2580-aaf9-11e9-9e67-6cc8813d9887.png)

![text injection in edit mode](https://user-images.githubusercontent.com/46688299/61578607-f4abf700-aaf9-11e9-87f1-a17924c9cb12.png)

![parts of the source code](https://user-images.githubusercontent.com/46688299/61578608-f83f7e00-aaf9-11e9-8e88-25c3c4165941.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Firefox 68.0 (64-bit)
 - Version API-Killer-WebSocket 1.0.2.11

**Additional context**
I can provide gists of the full strings if you need them.

**Comment by eladkarako** [comment]
that's weird, 
the web-extension creates a new script-element in every IFRAME on the page,
as a way to neutralize the API on that specific DOM (each IFRAME is given when created has its specific 'clean' set of JavaScript APIs).
I suspect that TinyMCE renders the result, much as I use in https://bin.eladkarako.com as an HTML, 
and not for example, as you might first suspect, a an styled text-area of some sort..
SCRIPT-elements should not be actually render as anything, 
<strong>but</strong> I know that if they would, they <strong>will</strong> be shown as "a lot of text".
I suspect that TinyMCE might apply a CSS-stylesheet that turns all elements visible, 
which means in that case I should include an inline "strong override style", saying, basically <code>style="display:none !important;"</code> on each of the injected SCRIPT-elements.

<hr/>

@SebastianTrautwein - I will generate a special version of <code>API-Killer-WebSocket</code> for you with a fix. Try install it and see if it makes any change.

[will update once I'll have it generated]

**Comment by eladkarako** [comment]
Uninstall your previous versions and try either one of those:
<ul>
<li>
for Firefox: 
<a href="https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/api_killer_websocket-1.0.3.2-an+fx.xpi">https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/api_killer_websocket-1.0.3.2-an+fx.xpi</a> (signed by Mozilla)
</li>
<li>
for Chrome:
<a href="https://github.com/eladkarako/chrome_extensions/releases/download/LatestChrome/API-Killer-WebSocket_1.0.3.2.zip">https://github.com/eladkarako/chrome_extensions/releases/download/LatestChrome/API-Killer-WebSocket_1.0.3.2.zip</a> (download, extract zip to a folder, load up as an unpacked extension in <code>chrome://extensions/</code>, in developer-mode)
</li>
</ul>

Let me know if it did it, and you're no longer see the 'a lot of text'.

**Comment by SebastianTrautwein** [comment]
@eladkarako Thank you for the quick reply. I removed the old addon, restarted the browser and then installed the new addon you provided. With that I went and typed around 20 characters in TinyMCE and then create a preview.

Funny enough now it produced even more unwanted text then before. I created a gist because the screenshot would be too big: https://gist.github.com/SebastianTrautwein/261b527901e5b8d90589647b405d3764

**Comment by eladkarako** [comment]
Gosh...
that text is my (scrambled) code.

I don't know why the content of the SCRIPT element is visible, 
by the example you've created (thanks! btw.) I don't think it is an issue that can be resolved by visibility tricks, 

apparently the structure of the script HTML (<code>&gt;</code> and <code>&lt;</code>...) is somehow gets broken down. 

the solution might be identifying and excluding working on TinyMCE iframes, 
or if the TinyMCE-engine allows some scripts to be injected and ignored by it (seems reasonable that it should) identify how it works...

...either why I should probably find-out couple of TinyMCE demo-websites to play-with...

sadly, this means that this bug will probably take a long (long) time to get fixed....
...sorry.

**Comment by eladkarako** [comment]
Notes for myself...
by the looks of it, the editor's engine tries to add
<code>&#x002F;&#x002F;&#x0020;&#x003E;</code> at the start, 
and <code>&#x002F;&#x002F;&#x0020;&#x005D;&#x005D;&#x003E;</code> at the end.
...I wonder if adding a fully XHTML script with some <code>&#x0027;&#x002F;&#x002A;&#x003C;&#x0021;&#x005B;&#x0043;&#x0044;&#x0041;&#x0054;&#x0041;&#x005B;&#x002A;&#x002F;&#x0027;</code> and <code>&#x0027;&#x002F;&#x002A;&#x005D;&#x005D;&#x003E;&#x002A;&#x002F;&#x0027;</code> might do the trick,

in the meanwhile I can't replicate yet the issues on https://www.tiny.cloud/docs/demo/full-featured/ - both preview and view-source seems to work fine.

that is indeed an IFRAME-rendering (the method is writing into it), 
some markups: <code>data-mce-....</code> and classes such as <code>mce-annotation</code> are too "content specific" to be useful...

**Comment by eladkarako** [comment]
adding this condition inside the main action on my web-extension seems nasty, 
but reasonable...

```js
if(null !== document.querySelector('body[id="tinymce"],body[class*="mce-content-body"]')) return; //exclude TinyMCE-IFRAMES
```

it identifies a page (can be an IFRAME) that is an TinyMCE-IFRAME.

**Comment by eladkarako** [comment]
@SebastianTrautwein try the latest from https://addons.mozilla.org/en-GB/firefox/addon/api-killer-websocket/
disable all my other web-extensions first, just in-case. there are others that uses similar script injections.

I've just included the minified code there and not the obfuscated one (less text.. :| )
and wrapped it with XHTML comments.

it probably won't work.. but lets try anyway.. :|

**Comment by eladkarako** [comment]
Note to myself.
if the TinyMCE iframe has issues with script injecting it might identify script blocks as different types of script, in that case it might be useful to add (long ago, previously removed) content-type (<code>text/javascript</code> or <code>application/javascript</code>) - trying to make the rendering engine to successfully identify the script block.... (?)

**Comment by eladkarako** [comment]
not going to change anything,
it is probably an issue that is very specific to a set of conditions (old browser/old TinyMCE engine/AdBlocking components)
the example page of the TinyMCE (latest version) seems stable, 
which is good for me.
