### ISSUE TITLE
MirrorX: toggle

### ISSUE THREAD

**Issue by grahamperrin** [eladkarako/chrome_extensions#6]
A fun extension, but I expected a second click on the button to revert things to normal. 

Instead, I found it necessary to disable the extension.

**Comment by eladkarako** [comment]
Yep. this is a pure CSS, no JavaScript experiment,
not a drop of JavaScript (for UI-management) is there as-well.
a switch will be nice, but for now enabling/disabling the web-extension is the way to go.
