### ISSUE TITLE
API-Killer-History: AMO: Support site: not found (404)

### ISSUE THREAD

**Issue by grahamperrin** [eladkarako/chrome_extensions#8]
https://addons.mozilla.org/addon/api-killer-history/ includes a reference to: 

- https://github.com/eladkarako/chrome_extensions/tree/master/API-Killer-History

– `https://github.com/eladkarako/chrome_extensions/tree/master/API-Killer-History` – that's 404, not found.

**Comment by grahamperrin** [comment]
Incidentally, https://addons.mozilla.org/en-GB/firefox/addon/spf-killer/ is no longer found. Is API-Killer-History a successor to SPF-Killer?

**Comment by eladkarako** [comment]
I know, the work on Mozilla is under review and the web-extensions are disabled in-the-meanwhile :|
but you can get them also on https://github.com/eladkarako/chrome_extensions/releases/tag/LatestFirefox
They are signed by Mozilla as well.

SPF-Killer is designed to only work on YouTube domains (for now), 
it does not disable the browser History capability, but gently asks YouTube to use a classic (not involving History-API manipulation) to browse around, it not always works.

History-API-Killer simply kills the History API and it breaks websites the do not have a fallback to using classic browsing (complete page load). YouTube will break when using this, a lot of its components are 'same-page'-'no-refresh'-based.
